from __future__ import annotations

SECTION_ALIASES: dict[str, tuple[str, ...]] = {
    "summary": (
        "summary",
        "professional summary",
        "profile summary",
        "career summary",
        "objective",
        "career objective",
        "profile",
        "about me",
    ),
    "skills": (
        "skills",
        "technical skills",
        "core skills",
        "key skills",
        "competencies",
        "technology stack",
        "tools and technologies",
    ),
    "experience": (
        "experience",
        "work experience",
        "professional experience",
        "employment history",
        "career history",
    ),
    "internships": (
        "internships",
        "internship",
        "industrial training",
        "training",
        "apprenticeship",
    ),
    "projects": (
        "projects",
        "academic projects",
        "personal projects",
        "key projects",
    ),
    "education": (
        "education",
        "educational qualifications",
        "academic details",
        "academics",
        "qualification",
    ),
    "certifications": (
        "certifications",
        "courses",
        "certificates",
        "licenses",
    ),
    "achievements": (
        "achievements",
        "accomplishments",
        "awards",
        "honors",
    ),
}

DEGREE_ALIASES: dict[str, tuple[str, ...]] = {
    "B.Tech": ("b tech", "b.tech", "b-tech", "b.tech.", "bachelor of technology"),
    "B.E": ("b e", "b.e", "bachelor of engineering"),
    "M.Tech": ("m tech", "m.tech", "master of technology"),
    "M.E": ("m e", "m.e", "master of engineering"),
    "MCA": ("mca", "master of computer applications"),
    "BCA": ("bca", "bachelor of computer applications"),
    "B.Sc": ("bsc", "b.sc", "bachelor of science"),
    "M.Sc": ("msc", "m.sc", "master of science"),
    "B.Com": ("bcom", "b.com", "bachelor of commerce"),
    "MBA": ("mba", "master of business administration"),
    "PGDM": ("pgdm", "post graduate diploma in management"),
    "Diploma": ("diploma", "polytechnic"),
    "Intermediate": ("intermediate", "mpc", "12th", "class 12"),
    "SSC": ("ssc", "class 10", "10th"),
}

SKILL_ALIASES: dict[str, tuple[str, ...]] = {
    "Python": ("python",),
    "C": ("c",),
    "C++": ("c++", "cpp"),
    "C#": ("c#", "dotnet", ".net"),
    "Java": ("java",),
    "JavaScript": ("javascript", "js"),
    "TypeScript": ("typescript", "ts"),
    "Node.js": ("node", "nodejs", "node.js"),
    "React": ("react", "reactjs", "react.js"),
    "Angular": ("angular", "angularjs"),
    "Vue.js": ("vue", "vuejs", "vue.js"),
    "Spring Boot": ("spring boot", "springboot"),
    "Spring": ("spring framework", "spring"),
    "Django": ("django",),
    "FastAPI": ("fastapi",),
    "Flask": ("flask",),
    "REST APIs": ("rest api", "rest apis", "restful api", "restful apis"),
    "GraphQL": ("graphql",),
    "SQL": ("sql",),
    "Oracle": ("oracle", "oracle db"),
    "MySQL": ("mysql",),
    "PostgreSQL": ("postgresql", "postgres"),
    "MongoDB": ("mongodb", "mongo db"),
    "Redis": ("redis",),
    "AWS": ("aws", "amazon web services"),
    "Azure": ("azure",),
    "GCP": ("gcp", "google cloud", "google cloud platform"),
    "Docker": ("docker",),
    "Kubernetes": ("kubernetes", "k8s"),
    "Terraform": ("terraform",),
    "Jenkins": ("jenkins",),
    "GitHub Actions": ("github actions",),
    "CI/CD": ("ci/cd", "ci cd", "continuous integration", "continuous delivery"),
    "Git": ("git", "github", "gitlab", "bitbucket"),
    "Data Structures": ("data structures", "dsa"),
    "Algorithms": ("algorithms",),
    "HTML": ("html", "html5"),
    "CSS": ("css", "css3"),
    "Bootstrap": ("bootstrap",),
    "Tailwind CSS": ("tailwind", "tailwind css"),
    "Linux": ("linux",),
    "Flutter": ("flutter",),
    "Android": ("android",),
    "Raspberry Pi": ("raspberry pi",),
    "Arduino": ("arduino",),
    "IoT": ("iot", "internet of things"),
    "Pandas": ("pandas",),
    "NumPy": ("numpy",),
    "Machine Learning": ("machine learning", "ml"),
    "Deep Learning": ("deep learning", "dl"),
    "NLP": ("nlp", "natural language processing"),
    "Excel": ("excel", "ms excel", "microsoft excel"),
}

INDIAN_LOCATIONS: dict[str, str] = {
    "ahmedabad": "Ahmedabad, Gujarat",
    "bengaluru": "Bengaluru, Karnataka",
    "bangalore": "Bengaluru, Karnataka",
    "chandigarh": "Chandigarh",
    "chennai": "Chennai, Tamil Nadu",
    "coimbatore": "Coimbatore, Tamil Nadu",
    "delhi": "Delhi",
    "gurgaon": "Gurugram, Haryana",
    "gurugram": "Gurugram, Haryana",
    "hyderabad": "Hyderabad, Telangana",
    "indore": "Indore, Madhya Pradesh",
    "jaipur": "Jaipur, Rajasthan",
    "kochi": "Kochi, Kerala",
    "kolkata": "Kolkata, West Bengal",
    "lucknow": "Lucknow, Uttar Pradesh",
    "mumbai": "Mumbai, Maharashtra",
    "nagpur": "Nagpur, Maharashtra",
    "noida": "Noida, Uttar Pradesh",
    "pune": "Pune, Maharashtra",
    "trivandrum": "Thiruvananthapuram, Kerala",
    "thiruvananthapuram": "Thiruvananthapuram, Kerala",
    "vadodara": "Vadodara, Gujarat",
    "vijayawada": "Vijayawada, Andhra Pradesh",
    "visakhapatnam": "Visakhapatnam, Andhra Pradesh",
}

SENSITIVE_PATTERNS: dict[str, str] = {
    "aadhaar": r"\b(?:aadhaar|aadhar)\b|\b\d{4}\s?\d{4}\s?\d{4}\b",
    "pan": r"(?:\bpan\b[^\n]{0,24}\b[A-Z]{5}\d{4}[A-Z]\b)|(?:\b[A-Z]{5}\d{4}[A-Z]\b[^\n]{0,12}\bpan\b)",
    "passport": r"\bpassport\b|\b[A-PR-WYa-pr-wy][1-9]\d{6}\b",
    "family_details": r"\b(father'?s name|mother'?s name|spouse|husband|wife|children)\b",
    "religion": r"\breligion\b",
    "caste": r"\bcaste\b",
    "marital_status": r"\bmarital status\b",
    "date_of_birth": r"\b(date of birth|dob)\b",
}

NOTICE_PERIOD_PATTERNS: tuple[str, ...] = (
    r"\bnotice period\b\s*[:\-]?\s*([A-Za-z0-9 +]+)",
    r"\bnp\b\s*[:\-]?\s*([A-Za-z0-9 +]+)",
)

CTC_PATTERNS: dict[str, str] = {
    "current_ctc": r"\b(current ctc|current compensation|current salary)\b\s*[:\-]?\s*([^\n,;]+)",
    "expected_ctc": r"\b(expected ctc|expected compensation|expected salary)\b\s*[:\-]?\s*([^\n,;]+)",
}

WORK_AUTHORIZATION_PATTERNS: tuple[str, ...] = (
    r"\b(?:work authorization|authorized to work|work permit|visa status)\b\s*[:\-]?\s*([^\n,;]+)",
    r"\b(?:us visa|h1b|citizen|permanent resident)\b\s*[:\-]?\s*([^\n,;]+)",
)

PREFERRED_LOCATION_PATTERNS: tuple[str, ...] = (
    r"\bpreferred location\b\s*[:\-]?\s*([^\n,;]+)",
    r"\bopen to relocate(?:ion)?\b\s*[:\-]?\s*([^\n,;]+)",
)

MONTH_NAMES: tuple[str, ...] = (
    "jan",
    "january",
    "feb",
    "february",
    "mar",
    "march",
    "apr",
    "april",
    "may",
    "jun",
    "june",
    "jul",
    "july",
    "aug",
    "august",
    "sep",
    "sept",
    "september",
    "oct",
    "october",
    "nov",
    "november",
    "dec",
    "december",
)
